export const ShipmentsData = [
  {
    id: "1",
    awb: "41785691423",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "RECEIVED",
  },
  {
    id: "2",
    awb: "41785691424",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "CANCELLED",
  },
  {
    id: "3",
    awb: "41785691425",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "ERROR",
  },
  {
    id: "4",
    awb: "41785691426",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "DELIVERED",
  },
  {
    id: "5",
    awb: "41785691426",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "ON HOLD",
  },
];
