export const ShipmentsData = [
  {
    id: "1",
    awb: "41785691423",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "RECEIVED",
  },
  {
    id: "2",
    awb: "6878691424",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "CANCELLED",
  },
  {
    id: "3",
    awb: "48687971425",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "ERROR",
  },
  {
    id: "4",
    awb: "487657691426",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "DELIVERED",
  },
  {
    id: "5",
    awb: "4176586788797",
    origin: "Cairo",
    originStreet: "Dokki, 22 Nile St.",
    destinationStreet: "Smoha, 22 max St.",
    destination: "Alexandria",
    status: "ON HOLD",
  },
];
